import {
  AcademicClass,
  CourseProgram,
  FeeCategory,
  ShiftInfo,
  Assignment,
  Submission,
  Quiz,
  Announcement,
  UserProfile,
} from "@/types";

export const SHIFTS_INFO: ShiftInfo[] = [
  {
    name: "Morning Shift",
    time: "8:00 AM – 12:00 PM",
    duration: "4 hours",
    bestSuitedFor: "School-going students (afternoon/evening school) & short course learners",
  },
  {
    name: "Evening Shift",
    time: "3:00 PM – 7:00 PM",
    duration: "4 hours",
    bestSuitedFor: "School-going students (morning school) & working individuals",
  },
];

export const ACADEMIC_CLASSES: AcademicClass[] = [
  {
    id: "pre-primary",
    category: "pre-primary",
    name: "Pre-Primary & Primary Section",
    grades: "Nursery to Class 5",
    subjects: [
      "English",
      "Urdu",
      "Mathematics",
      "General Science",
      "Islamiyat",
      "Social Studies",
      "General Knowledge",
    ],
    monthlyFee: 2500,
    description:
      "Montessori-based early learning through primary classes focusing on reading, writing, handwriting improvement, spoken English basics, numeracy, and Islamic values.",
  },
  {
    id: "middle",
    category: "middle",
    name: "Middle Section",
    grades: "Class 6 to Class 8",
    subjects: [
      "English",
      "Urdu",
      "Mathematics",
      "General Science",
      "Islamiyat",
      "Pakistan Studies / Social Studies",
      "Computer Science",
    ],
    monthlyFee: 4000,
    description:
      "Core foundation building, exam preparation techniques, and strong analytical preparation for Matriculation.",
  },
  {
    id: "matric",
    category: "matric",
    name: "Matric Section",
    grades: "Class 9 & Class 10",
    groups: ["Science Group (Pre-Med/Pre-Eng)", "Arts / General Group"],
    subjects: [
      "Physics",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Computer Science",
      "English",
      "Urdu",
      "Islamiyat",
      "Pakistan Studies",
    ],
    monthlyFee: 2300,
    packageFee: 7500,
    description:
      "Comprehensive BISE Rawalpindi Board exam preparation with regular chapter-wise tests, solved past papers, and proven guess papers.",
  },
  {
    id: "intermediate",
    category: "intermediate",
    name: "Intermediate (HSSC / FSc / ICS / I.Com / FA)",
    grades: "Class 11 & Class 12",
    groups: [
      "Pre-Medical",
      "Pre-Engineering",
      "ICS (Computer Science)",
      "Commerce (I.Com)",
      "General Arts",
    ],
    subjects: [
      "Physics",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Computer Science",
      "Statistics",
      "Principles of Accounting",
      "Economics",
      "Business Studies",
      "English",
      "Urdu",
      "Islamiyat",
      "Pakistan Studies",
    ],
    monthlyFee: 2800,
    packageFee: 9500,
    description:
      "Rigorous board coaching with concept masterclasses, numerical drills, formula handbooks, and mock board exams to secure top merit positions.",
  },
  {
    id: "bachelor",
    category: "bachelor",
    name: "Bachelor's Degree Coaching & Support",
    grades: "BS 4-Year Programs (Subject-Wise)",
    groups: ["BS CS / SE", "BBA", "BS Math & Sciences", "BS English", "B.Ed / ADE"],
    subjects: [
      "Programming Fundamentals & OOP",
      "Calculus & Linear Algebra",
      "Financial Accounting & Economics",
      "Business Math & Statistics",
      "Core Physics / Chemistry / Biology",
      "Academic Writing & Presentations",
    ],
    monthlyFee: 3500,
    description:
      "Subject-wise tutoring and exam preparation support designed to help university students excel in midterms, finals, semester projects, and thesis presentations.",
  },
  {
    id: "entry-test",
    category: "entry-test",
    name: "Entry Test Preparation (MDCAT / ECAT / NET)",
    grades: "Medical & Engineering Aspirants",
    groups: ["MDCAT (PMDC Pattern)", "ECAT (UET Pattern)", "NUST NET / FAST NU / GIKI"],
    subjects: [
      "Biology Concept Mastery",
      "Physics Conceptual & Numerical MCQs",
      "Chemistry Reaction Mechanisms",
      "Higher Mathematics Speed Drills",
      "English & Logical Reasoning",
    ],
    monthlyFee: 6500,
    packageFee: 35000,
    description:
      "Top-tier national entrance test coaching (KIPS/Stars style) covering complete FSc 1st & 2nd year syllabus with weekly computerized mock tests and ranking analytics.",
  },
];

export const SHORT_COURSES: CourseProgram[] = [
  {
    id: "graphic-design",
    title: "Graphic Designing",
    category: "digital-skills",
    duration: "2 Months",
    fee: 8000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Adobe Photoshop", "Adobe Illustrator", "Canva Pro", "Logo Design & Branding"],
    description: "Master modern visual aesthetics, social media creatives, flyer/poster design, vector illustration, and freelance portfolio building.",
    popular: true,
  },
  {
    id: "web-dev",
    title: "Web Development Basics",
    category: "digital-skills",
    duration: "2 Months",
    fee: 8500,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["HTML5 & Semantic Web", "CSS3 & Responsive Design", "JavaScript Fundamentals", "Git & GitHub"],
    description: "Learn to build modern, responsive web pages from scratch with hands-on live projects and website deployment.",
    popular: true,
  },
  {
    id: "python-ai",
    title: "Python Programming & AI Basics",
    category: "digital-skills",
    duration: "6 Weeks",
    fee: 6500,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Python Core Syntax", "Data Structures & Functions", "Automation Scripts", "Intro to AI & LLMs"],
    description: "Get started with the world's most versatile programming language, logic building, and real-world AI applications.",
    popular: true,
  },
  {
    id: "data-science",
    title: "Data Science & Analysis",
    category: "digital-skills",
    duration: "2 Months",
    fee: 9000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Pandas & NumPy", "Data Visualization (Matplotlib)", "SQL Basics", "Excel Analytics"],
    description: "Transform raw data into meaningful business insights, charts, dashboards, and automated analysis reports.",
  },
  {
    id: "freelancing",
    title: "Freelancing & Digital Marketing",
    category: "digital-skills",
    duration: "6 Weeks",
    fee: 6000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Upwork & Fiverr Profile Setup", "SEO Basics", "Social Media Marketing", "Client Proposal Writing"],
    description: "Kickstart your international freelance career, win global clients, handle payments in Pakistan, and master online marketing.",
    popular: true,
  },
  {
    id: "wordpress",
    title: "WordPress & Website Building",
    category: "digital-skills",
    duration: "4 Weeks",
    fee: 5000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Elementor Page Builder", "WooCommerce Store Setup", "Domain & Hosting Setup", "SEO & Speed Optimization"],
    description: "Create professional business websites, e-commerce stores, and blogs with zero coding required.",
  },
  {
    id: "ms-office",
    title: "Microsoft Office Suite",
    category: "digital-skills",
    duration: "4 Weeks",
    fee: 4000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["MS Word Document Formatting", "MS Excel Formulas & Charts", "MS PowerPoint Presentations", "Office Productivity"],
    description: "Essential office computing skills for students, job applicants, and office executives.",
  },
  {
    id: "ielts",
    title: "IELTS Preparation (Academic & General)",
    category: "language",
    duration: "2 Months",
    fee: 9000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Listening Module Drills", "Reading Comprehension Strategies", "Writing Task 1 & 2 Templates", "Speaking Mock Interviews"],
    description: "Target Band 7.5+ with expert Cambridge-certified strategies, regular mock tests, and 1-on-1 speaking evaluations.",
    popular: true,
  },
  {
    id: "spoken-english",
    title: "Spoken English & Grammar",
    category: "language",
    duration: "6 Weeks",
    fee: 5000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["Everyday Conversational Fluency", "Pronunciation & Vocabulary", "Core Grammar & Tenses", "Public Speaking Confidence"],
    description: "Overcome hesitation, master natural pronunciation, and communicate confidently in academic and professional settings.",
  },
  {
    id: "css-pms",
    title: "CSS / PMS Coaching",
    category: "competitive",
    duration: "3 Months",
    fee: 12000,
    feeType: "one-time",
    shiftOptions: ["Morning Shift (8-12)", "Evening Shift (3-7)"],
    toolsOrModules: ["English Essay & Precis", "Current & Pakistan Affairs", "Islamic Studies & GK", "Optional Subject Mentorship"],
    description: "Strategic preparation for competitive civil service exams guided by experienced officers and subject mentors.",
    popular: true,
  },
];

export const FEE_TABLES: FeeCategory[] = [
  {
    section: "5.1",
    title: "Pre-Primary & Primary Section (Nursery – Class 5)",
    description: "Monthly tuition fees covering all subjects with personalized attention.",
    items: [
      { name: "Nursery / Prep (Play Group)", fee: 2500, duration: "Per Month", note: "Montessori-based foundational learning" },
      { name: "Class 1 – Class 2", fee: 3000, duration: "Per Month", note: "All subjects included" },
      { name: "Class 3 – Class 5", fee: 3500, duration: "Per Month", note: "All subjects + spoken English coaching" },
    ],
  },
  {
    section: "5.2",
    title: "Middle Section (Class 6 – Class 8)",
    description: "Monthly tuition fees for all subjects combined.",
    items: [
      { name: "Class 6 (All Subjects)", fee: 4000, duration: "Per Month", note: "Includes Math, Science, English, Urdu, Islamiyat, Pak Studies, CS" },
      { name: "Class 7 (All Subjects)", fee: 4500, duration: "Per Month", note: "Includes all board-prescribed subjects" },
      { name: "Class 8 (All Subjects)", fee: 5000, duration: "Per Month", note: "Matric foundation and intensive test series" },
    ],
  },
  {
    section: "5.3",
    title: "Matric Section (Class 9 & Class 10)",
    description: "Choose subject-wise tuition or discounted full-group packages.",
    items: [
      { name: "Physics", fee: "Class 9: PKR 2,300 | Class 10: PKR 2,500", duration: "Per Month", note: "Theory + Numerical problem solving" },
      { name: "Chemistry", fee: "Class 9: PKR 2,300 | Class 10: PKR 2,500", duration: "Per Month", note: "Equations & concept clarity" },
      { name: "Biology", fee: "Class 9: PKR 2,300 | Class 10: PKR 2,500", duration: "Per Month", note: "Diagrams & past papers" },
      { name: "Mathematics", fee: "Class 9: PKR 2,300 | Class 10: PKR 2,500", duration: "Per Month", note: "Speed drills & step-by-step proofs" },
      { name: "Computer Science", fee: "Class 9: PKR 2,000 | Class 10: PKR 2,200", duration: "Per Month", note: "Programming logic & concepts" },
      { name: "English", fee: "Class 9: PKR 1,800 | Class 10: PKR 2,000", duration: "Per Month", note: "Grammar & essay writing" },
      { name: "Urdu", fee: "Class 9: PKR 1,600 | Class 10: PKR 1,800", duration: "Per Month", note: "Literature & grammar" },
      { name: "Islamiyat / Pak Studies", fee: "Class 9: PKR 1,300 | Class 10: PKR 1,500", duration: "Per Month", note: "Board exam targeted notes" },
      { name: "Full Science Group Package", fee: "Class 9: PKR 7,500 | Class 10: PKR 8,000", duration: "Per Month", note: "All subjects included (Save up to 40%!)" },
      { name: "Full Arts / General Group Package", fee: "Class 9: PKR 6,000 | Class 10: PKR 6,500", duration: "Per Month", note: "All general subjects included" },
    ],
  },
  {
    section: "5.4",
    title: "Intermediate Section (Class 11 & Class 12 / FSc / ICS)",
    description: "Subject-wise enrollment and discounted group packages.",
    items: [
      { name: "Physics / Chemistry / Biology / Math", fee: "Class 11: PKR 2,800 | Class 12: PKR 3,000", duration: "Per Subject / Month", note: "Subject specialist coaching" },
      { name: "Computer Science", fee: "Class 11: PKR 2,500 | Class 12: PKR 2,800", duration: "Per Month", note: "C++ / DBMS / Web" },
      { name: "Statistics / Accounting / Business", fee: "Class 11: PKR 2,300 | Class 12: PKR 2,500", duration: "Per Month", note: "Commerce & ICS electives" },
      { name: "English", fee: "Class 11: PKR 2,300 | Class 12: PKR 2,500", duration: "Per Month", note: "Grammar, translation & comprehension" },
      { name: "Urdu / Islamiyat / Pak Studies", fee: "Class 11: PKR 1,600 - 1,800 | Class 12: PKR 1,800 - 2,000", duration: "Per Month", note: "Compulsory subjects" },
      { name: "Pre-Medical Group Package", fee: "Class 11: PKR 9,500 | Class 12: PKR 10,000", duration: "Per Month", note: "Physics, Chem, Bio, Eng, Urdu" },
      { name: "Pre-Engineering Group Package", fee: "Class 11: PKR 9,500 | Class 12: PKR 10,000", duration: "Per Month", note: "Physics, Chem, Math, Eng, Urdu" },
      { name: "ICS Group Package", fee: "Class 11: PKR 9,000 | Class 12: PKR 9,500", duration: "Per Month", note: "Math, CS/Stats, Physics, Eng, Urdu" },
      { name: "Commerce Group (I.Com) Package", fee: "Class 11: PKR 8,500 | Class 12: PKR 9,000", duration: "Per Month", note: "Accounting, Business, Stats, Econ" },
      { name: "General Arts Group Package", fee: "Class 11: PKR 7,500 | Class 12: PKR 8,000", duration: "Per Month", note: "All elective & compulsory subjects" },
    ],
  },
  {
    section: "5.5",
    title: "Entry Test Preparation & Short Courses",
    description: "Dedicated full courses and intensive crash programs.",
    items: [
      { name: "MDCAT Full Course (6 Months)", fee: 35000, duration: "Full Course (or 6,500/mo)", note: "Includes complete PMDC syllabus & full test series" },
      { name: "ECAT Full Course (6 Months)", fee: 32000, duration: "Full Course (or 6,000/mo)", note: "Includes UET pattern tests & speed drills" },
      { name: "MDCAT / ECAT Crash Course", fee: 15000, duration: "6-8 Weeks (One-time)", note: "Intensive 4 hours/day mock prep" },
      { name: "IELTS Preparation", fee: 9000, duration: "2 Months (One-time)", note: "All 4 modules + mock interviews" },
      { name: "CSS / PMS Coaching", fee: 12000, duration: "3 Months (One-time)", note: "Compulsory & optional guidance" },
      { name: "Graphic Designing", fee: 8000, duration: "2 Months (One-time)", note: "Photoshop, Illustrator, Canva" },
      { name: "Web Development Basics", fee: 8500, duration: "2 Months (One-time)", note: "HTML, CSS, JS, Git" },
      { name: "Python & AI Basics", fee: 6500, duration: "6 Weeks (One-time)", note: "Coding fundamentals & AI tools" },
      { name: "Data Science & Analysis", fee: 9000, duration: "2 Months (One-time)", note: "Pandas, NumPy, SQL, Excel" },
      { name: "Freelancing & Digital Marketing", fee: 6000, duration: "6 Weeks (One-time)", note: "Upwork, Fiverr, SEO, SMM" },
      { name: "WordPress & Website Building", fee: 5000, duration: "4 Weeks (One-time)", note: "Elementor & eCommerce" },
      { name: "Microsoft Office Suite", fee: 4000, duration: "4 Weeks (One-time)", note: "Word, Excel, PowerPoint" },
      { name: "Spoken English & Grammar", fee: 5000, duration: "6 Weeks (One-time)", note: "Fluency & public speaking" },
    ],
  },
  {
    section: "5.6",
    title: "Admission, Registration & Other Institutional Charges",
    description: "One-time registration fees, discounts, and policy rules.",
    items: [
      { name: "Admission Fee", fee: 2000, duration: "One-Time", note: "Applicable for all new students, all levels" },
      { name: "Registration & Prospectus Fee", fee: 500, duration: "One-Time", note: "Includes official Academy Prospectus & Student ID Card" },
      { name: "Monthly Test Series (Matric/Inter)", fee: 500, duration: "Optional / Month", note: "Weekly quizzes + monthly comprehensive assessment" },
      { name: "MDCAT / ECAT Mock Test Series", fee: 1500, duration: "Optional Add-on", note: "Includes 12 full-length simulated mock exam papers with analytics" },
      { name: "Sibling Discount", fee: "10% OFF", duration: "Every Month", note: "Applied automatically on tuition fees from the 2nd sibling onward" },
      { name: "Late Fee Surcharge", fee: "PKR 200 / week", duration: "After 10th of Month", note: "Tuition is due by 10th of each month; surcharge applies afterward" },
    ],
  },
];

export const DEMO_USERS: UserProfile[] = [
  {
    id: "student-demo-1",
    email: "student@mindflare.pk",
    full_name: "Ahmad Raza",
    role: "student",
    phone: "0312-3456789",
    enrolled_class: "Class 10 - Science Group",
    shift: "Evening",
    status: "active",
    created_at: "2026-01-15",
  },
  {
    id: "teacher-demo-1",
    email: "teacher@mindflare.pk",
    full_name: "Prof. Tariq Mahmood (M.Phil Physics)",
    role: "teacher",
    phone: "0300-9876543",
    enrolled_class: "Senior Physics & MDCAT Faculty",
    shift: "Morning",
    status: "active",
    created_at: "2025-08-10",
  },
  {
    id: "admin-demo-1",
    email: "admin@mindflare.pk",
    full_name: "Principal Administration",
    role: "admin",
    phone: "0317-5790206",
    enrolled_class: "Mind Flare Management",
    shift: "Morning",
    status: "active",
    created_at: "2024-01-01",
  },
];

export const DEMO_ASSIGNMENTS: Assignment[] = [
  {
    id: "asg-1",
    title: "Physics: Newton's Laws of Motion & Friction Numericals",
    subject: "Physics",
    class_name: "Class 10 - Science Group",
    teacher_id: "teacher-demo-1",
    teacher_name: "Prof. Tariq Mahmood",
    description: "Solve questions 1 through 8 from Chapter 3 past papers. Show complete free-body diagrams, formulas, and step-by-step units.",
    due_date: "2026-09-25",
    max_score: 25,
    created_at: "2026-09-15",
  },
  {
    id: "asg-2",
    title: "Chemistry: Balancing Redox Reactions & Stoichiometry",
    subject: "Chemistry",
    class_name: "Class 10 - Science Group",
    teacher_id: "teacher-demo-2",
    teacher_name: "Dr. Samina Khan",
    description: "Balance the 5 chemical equations provided in the handout and calculate the mass of products formed under STP conditions.",
    due_date: "2026-09-28",
    max_score: 20,
    created_at: "2026-09-16",
  },
  {
    id: "asg-3",
    title: "English: Descriptive Essay on 'The Power of Artificial Intelligence'",
    subject: "English",
    class_name: "Class 10 - Science Group",
    teacher_id: "teacher-demo-3",
    teacher_name: "Sir Usama",
    description: "Write a 300-350 word essay highlighting benefits, ethical concerns, and future implications. Use advanced transitional vocabulary.",
    due_date: "2026-09-30",
    max_score: 15,
    created_at: "2026-09-14",
  },
];

export const DEMO_SUBMISSIONS: Submission[] = [
  {
    id: "sub-1",
    assignment_id: "asg-1",
    student_id: "student-demo-1",
    student_name: "Ahmad Raza",
    submission_text: "Attached are my full solutions for numericals 1-8 with step-by-step vector calculations for friction coefficients on inclined planes.",
    file_name: "Ahmad_Physics_Ch3_Numericals.pdf",
    submitted_at: "2026-09-16 18:30",
    score: 24,
    feedback: "Exceptional precision in units and vector resolution! Minor rounding on question 6.",
    status: "graded",
  },
];

export const DEMO_QUIZZES: Quiz[] = [
  {
    id: "quiz-physics-1",
    title: "Class 10 Physics: Kinematics & Vectors Challenge",
    subject: "Physics",
    class_name: "Class 10 - Science",
    teacher_name: "Prof. Tariq Mahmood",
    duration_minutes: 10,
    created_at: "2026-09-12",
    questions: [
      {
        id: "q1",
        question: "What is the SI unit of momentum?",
        options: ["kg·m/s", "N/s", "J·s", "kg/m·s²"],
        correct_index: 0,
        explanation: "Momentum is mass times velocity (p = m × v), hence its SI unit is kg·m/s (or N·s).",
      },
      {
        id: "q2",
        question: "A car accelerates uniformly from rest to 20 m/s in 5 seconds. What is its acceleration?",
        options: ["2 m/s²", "4 m/s²", "10 m/s²", "100 m/s²"],
        correct_index: 1,
        explanation: "Acceleration a = (v_f - v_i) / t = (20 - 0) / 5 = 4 m/s².",
      },
      {
        id: "q3",
        question: "When a body moves in a circular path with constant speed, its acceleration is:",
        options: ["Zero", "Directed towards the center", "Directed away from the center", "Tangential to the circle"],
        correct_index: 1,
        explanation: "Centripetal acceleration is always directed towards the center of the circular path.",
      },
      {
        id: "q4",
        question: "Which Newton's law explains the recoil of a gun?",
        options: ["First Law", "Second Law", "Third Law", "Law of Gravitation"],
        correct_index: 2,
        explanation: "Newton's Third Law states every action has an equal and opposite reaction.",
      },
      {
        id: "q5",
        question: "What is the coefficient of static friction compared to kinetic friction?",
        options: ["Always smaller", "Always greater", "Always equal", "Zero"],
        correct_index: 1,
        explanation: "Static friction is greater than kinetic friction because more force is required to break initial interlocking of surfaces.",
      },
    ],
  },
  {
    id: "quiz-cs-1",
    title: "Web & Computer Science Fundamentals Quiz",
    subject: "Computer Science",
    class_name: "Short Courses & ICS",
    teacher_name: "Engr. Bilal",
    duration_minutes: 8,
    created_at: "2026-09-14",
    questions: [
      {
        id: "qc1",
        question: "Which HTML tag is used for the largest primary heading?",
        options: ["<heading>", "<h6>", "<h1>", "<head>"],
        correct_index: 2,
        explanation: "<h1> is the semantic top-level heading in HTML.",
      },
      {
        id: "qc2",
        question: "What does CSS stand for?",
        options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer System Syntax", "Colorful Style Script"],
        correct_index: 1,
        explanation: "CSS stands for Cascading Style Sheets.",
      },
      {
        id: "qc3",
        question: "In Python, which keyword is used to define a function?",
        options: ["func", "function", "def", "define"],
        correct_index: 2,
        explanation: "Python uses 'def' followed by function name to declare functions.",
      },
      {
        id: "qc4",
        question: "Which data structure operates on a First-In-First-Out (FIFO) principle?",
        options: ["Stack", "Queue", "Tree", "Array"],
        correct_index: 1,
        explanation: "Queue follows First-In-First-Out (FIFO).",
      },
    ],
  },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "anc-1",
    title: "📢 Monthly Comprehensive Grand Test Series Schedule",
    content: "The monthly test series for Matric (Class 9 & 10) and Inter (Class 11 & 12) will commence on Monday, September 22nd. Attendance is mandatory (minimum 80% required as per academy rules).",
    author_name: "Administration Office",
    target_audience: "all",
    priority: "urgent",
    date: "2026-09-16",
  },
  {
    id: "anc-2",
    title: "✨ Special Sunday MDCAT & ECAT Speed Drills",
    content: "Special high-yield numerical problem solving session for entry test students will be conducted this Sunday from 9:00 AM to 1:00 PM. Handouts will be provided.",
    author_name: "Prof. Tariq Mahmood",
    target_audience: "students",
    priority: "normal",
    date: "2026-09-15",
  },
  {
    id: "anc-3",
    title: "💳 Tuition Fee Reminder (Due by 10th of every month)",
    content: "All parents and students are reminded that monthly tuition fees must be cleared by the 10th to avoid the weekly surcharge of PKR 200. Sibling discounts (10%) are automatically deducted on fee vouchers.",
    author_name: "Accounts Department",
    target_audience: "all",
    priority: "normal",
    date: "2026-09-10",
  },
];
